### ISSUE TITLE
BadMethodCallException

### ISSUE THREAD

**Issue by iolson** [laravelista/Ekko#1]
After adding to `composer.json` file and doing `composer update`, I get this when the command of `php artisan clear-compiled` gets called.

```
[2015-05-22 15:14:01] local.ERROR: exception 'BadMethodCallException' with message 'Call to undefined method [package]' in /Users/iolson/Projects/laravel-project/vendor/compiled.php:4476
Stack trace:
#0 /Users/iolson/Projects/laravel-project/vendor/laravelista/ekko/src/Laravelista/Ekko/EkkoServiceProvider.php(21): Illuminate\Support\ServiceProvider->__call('package', Array)
#1 /Users/iolson/Projects/laravel-project/vendor/laravelista/ekko/src/Laravelista/Ekko/EkkoServiceProvider.php(21): Laravelista\Ekko\EkkoServiceProvider->package('laravelista/ekk...')
#2 [internal function]: Laravelista\Ekko\EkkoServiceProvider->boot()
#3 /Users/iolson/Projects/laravel-project/vendor/compiled.php(925): call_user_func_array(Array, Array)
#4 /Users/iolson/Projects/laravel-project/vendor/compiled.php(1526): Illuminate\Container\Container->call(Array)
#5 /Users/iolson/Projects/laravel-project/vendor/compiled.php(1518): Illuminate\Foundation\Application->bootProvider(Object(Laravelista\Ekko\EkkoServiceProvider))
#6 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Laravelista\Ekko\EkkoServiceProvider), 26)
#7 /Users/iolson/Projects/laravel-project/vendor/compiled.php(1519): array_walk(Array, Object(Closure))
#8 /Users/iolson/Projects/laravel-project/vendor/compiled.php(1837): Illuminate\Foundation\Application->boot()
#9 /Users/iolson/Projects/laravel-project/vendor/compiled.php(1314): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#10 /Users/iolson/Projects/laravel-project/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(195): Illuminate\Foundation\Application->bootstrapWith(Array)
#11 /Users/iolson/Projects/laravel-project/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(92): Illuminate\Foundation\Console\Kernel->bootstrap()
#12 /Users/iolson/Projects/laravel-project/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main}  

```

**Comment by mabasic** [comment]
Are you using L5?

**Comment by mabasic** [comment]
I have just pushed a new version `1.0.3` where that issue has been fixed. Let me just test and confirm it abd I will get back at you.

**Comment by iolson** [comment]
Yes, I'm using Laravel 5.0.X

**Comment by iolson** [comment]
@mabasic This has fixed the issue.

**Comment by mabasic** [comment]
Nice, it works on L4 and L5 now.
